### ISSUE TITLE
SessionFactory

### ISSUE THREAD

**Issue by pawaitemadisoncollege** [nmadam/YouDeserveBetterToday#5]
Hi Nancy,

I'm looking at your repository and I don't see any issues around the sessionFactory. I'm wondering if any of the changes related to the problems you were having were actually pushed up?  Looks like there hasn't been a push in a couple days, so it would be a good idea to push what you did this afternoon up so it is backed up.

**Comment by nmadam** [comment]
I pushed on Sunday when I worked on it last. I'll push again though.

Sent from my U.S. Cellular® Smartphone-------- Original message --------From: Paula Waite notifications@github.com Date: 03/01/2016  4:17 PM  (GMT-06:00) To: nmadam/YouDeserveBetterToday YouDeserveBetterToday@noreply.github.com Subject: [YouDeserveBetterToday] SessionFactory (#5) 
Hi Nancy,

I'm looking at your repository and I don't see any issues around the sessionFactory. I'm wondering if any of the changes related to the problems you were having were actually pushed up?  Looks like there hasn't been a push in a couple days, so it would be a good idea to push what you did this afternoon up so it is backed up.
